
import { App, User, UserRole, AppStatus } from './types';

export const MOCK_USERS: User[] = [
  { id: 1, name: 'Admin User', email: 'admin@appstore.com', role: UserRole.ADMIN },
  { id: 2, name: 'Dev One', email: 'dev1@appstore.com', role: UserRole.DEVELOPER },
  { id: 3, name: 'Dev Two', email: 'dev2@appstore.com', role: UserRole.DEVELOPER },
];

export const MOCK_APPS: App[] = [
  {
    id: 1,
    name: 'PhotoSnap Editor',
    packageName: 'com.photosnap.editor',
    icon: 'https://picsum.photos/seed/app1/256/256',
    apkPath: '/uploads/apks/photosnap.apk',
    screenshots: [
      'https://picsum.photos/seed/s1a/1080/1920',
      'https://picsum.photos/seed/s1b/1080/1920',
      'https://picsum.photos/seed/s1c/1080/1920',
      'https://picsum.photos/seed/s1d/1080/1920',
    ],
    description: 'Powerful and easy-to-use photo editor for stunning results.',
    longDescription: 'PhotoSnap Editor offers a wide range of tools to enhance your photos. From basic adjustments like brightness and contrast to advanced features like selective color and custom filters, it has everything you need to make your pictures stand out. The intuitive interface makes it easy for beginners, while professionals will appreciate the depth of control.',
    status: AppStatus.APPROVED,
    developerId: 2,
    developerName: 'Dev One',
    version: '2.1.0',
    size: '98 MB',
    rating: 4.7,
    downloads: '5M+',
  },
  {
    id: 2,
    name: 'FinanceFlow',
    packageName: 'com.finance.flow',
    icon: 'https://picsum.photos/seed/app2/256/256',
    apkPath: '/uploads/apks/financeflow.apk',
    screenshots: [
      'https://picsum.photos/seed/s2a/1080/1920',
      'https://picsum.photos/seed/s2b/1080/1920',
    ],
    description: 'Track your expenses and manage your budget effortlessly.',
    longDescription: 'Take control of your finances with FinanceFlow. Easily track your spending, create budgets, and get insights into your financial habits. Connect your bank accounts for automatic transaction syncing and see all your money in one place.',
    status: AppStatus.APPROVED,
    developerId: 3,
    developerName: 'Dev Two',
    version: '1.5.2',
    size: '45 MB',
    rating: 4.9,
    downloads: '1M+',
  },
  {
    id: 3,
    name: 'TaskMaster Pro',
    packageName: 'com.taskmaster.pro',
    icon: 'https://picsum.photos/seed/app3/256/256',
    apkPath: '/uploads/apks/taskmaster.apk',
    screenshots: [
       'https://picsum.photos/seed/s3a/1080/1920',
       'https://picsum.photos/seed/s3b/1080/1920',
       'https://picsum.photos/seed/s3c/1080/1920',
    ],
    description: 'A new way to organize your daily tasks and projects.',
    longDescription: 'Boost your productivity with TaskMaster Pro. Whether you are managing personal to-dos or complex team projects, our flexible boards, lists, and cards will help you stay organized and on track. Collaborate with your team in real-time and achieve your goals faster.',
    status: AppStatus.PENDING,
    developerId: 2,
    developerName: 'Dev One',
    version: '1.0.0',
    size: '60 MB',
    rating: 0,
    downloads: '0',
  },
   {
    id: 4,
    name: 'WeatherWise',
    packageName: 'com.weather.wise',
    icon: 'https://picsum.photos/seed/app4/256/256',
    apkPath: '/uploads/apks/weatherwise.apk',
    screenshots: [
       'https://picsum.photos/seed/s4a/1080/1920',
       'https://picsum.photos/seed/s4b/1080/1920',
    ],
    description: 'Hyperlocal weather forecasts with beautiful visualizations.',
    longDescription: 'Get the most accurate weather information with WeatherWise. Featuring down-to-the-minute precipitation forecasts, detailed hourly and daily predictions, and a beautiful, intuitive interface. Stay ahead of the weather with severe weather alerts and customizable widgets.',
    status: AppStatus.REJECTED,
    developerId: 3,
    developerName: 'Dev Two',
    version: '3.2.1',
    size: '35 MB',
    rating: 4.2,
    downloads: '500K+',
  }
];
